name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Build plugin
              run: |
                  npm install
                  npm run build

            # Package the required files into a zip
            - name: Package Zip
              run: |
                  mkdir ${{ github.event.repository.name }}
                  cp main.js manifest.json styles.css README.md ${{ github.event.repository.name }}
                  zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"
                  
                  gh release create "$tag" \
                    --title="$tag" \
                    --draft \
                    main.js manifest.json styles.css ${{ github.event.repository.name }}.zip

    generate-changelog:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: BobAnkh/auto-generate-changelog@v1.2.5
                with:
                    REPO_NAME: 'J-Barta/qb-reader-parser'
                    ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
                    PATH: 'CHANGELOG.md'
                    COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
                    TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
